# apps/frontend/config/routing.yml
category:
  url:      /category/:slug.:sf_format
  class:    sfPropelRoute
  param:    { module: category, action: show, sf_format: html }
  options:  { model: JobeetCategory, type: object }
  requirements:
    sf_format: (?:html|atom)
  
job:
  class:   sfPropelRouteCollection
  options:
    model:          JobeetJob
    column:         token
    object_actions: { publish: PUT, extend: PUT }
  requirements:
    token: \w+
 
job_show_user:
  url:     /job/:company_slug/:location_slug/:token/:position_slug
  class:   sfPropelRoute
  options: 
    model: JobeetJob
    type: object
    method_for_criteria: doSelectActive
  param:   { module: job, action: show }
  requirements:
    token: \w+
    sf_method: [GET]
        
# default rules
homepage:
  url:   /
  param: { module: job, action: index }
 
#default_index:
#  url:   /:module
#  param: { action: index }
#
#default:
#  url:   /:module/:action/*